### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by digcat** [marsbard/grua#7]
to enable windows to work with grua, the find_bridge_ip function doesnt work in a windows environment, perhaps netifaces would be a better way?

$ ./grua
File not found
Traceback (most recent call last):
  File "./grua", line 3, in <module>
    from grua import grua
  File "build\bdist.win-amd64\egg\grua\grua.py", line 7, in <module>
  File "build\bdist.win-amd64\egg\grua\util.py", line 70, in find_bridge_ip
Exception: Could not find either 'ip' or 'ifconfig' in PATH

https://pypi.python.org/pypi/netifaces

def find_bridge_ip():

```
try:
    command = ["ip", "addr", "show", "dev", "docker0"]
    sp = subprocess.Popen(command, stdout=subprocess.PIPE)

    output = subprocess.check_output(('grep', 'inet'), stdin=sp.stdout).strip().split()[1].split('/')[0]

    done = True
```

**Comment by marsbard** [comment]
Happy to take pull requests to make windows work as long as they don't break current functionality but unfortunately my windows system won't run docker so I cannot test

**Comment by digcat** [comment]
yes, just got docker windows installed, so flushing out issues which 
will come up.  was looking at that library as a possible work around, it 
demands install a vc++ compiler, but installs cleanly on 27.

**Comment by digcat** [comment]
latest pull i get 

$ ./grua
Traceback (most recent call last):
  File "./grua", line 3, in <module>
    from grua import grua
  File "build\bdist.win-amd64\egg\grua\grua.py", line 7, in <module>
  File "build\bdist.win-amd64\egg\grua\util.py", line 71, in find_bridge_ip
UnboundLocalError: local variable 'sp' referenced before assignment

**Comment by marsbard** [comment]
grr it needs a tab at line 71
